package com.fis.springjpa.Employee;

import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController // This means that this class is a Controller
@RequestMapping(path = "/employee") // This means URL's start with /demo (after Application path)
public class EmployeeController {
	@Autowired
	// Which is auto-generated by Spring, we will use it to handle the data
	private EmployeeRepository employeeRepository;

	@PostMapping(path = "/add") // Map ONLY POST Requests
	public @ResponseBody String addNewEmployee(@RequestParam String name, @RequestParam String email) {
		Employee n = new Employee();
		n.setName(name);
		n.setEmail(email);
		employeeRepository.save(n);
		return "Saved";
	}
	
	@PostMapping
	public String addEmployee(@RequestBody Employee employee) {
		employeeRepository.save(employee);
		return "Saved";
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<Employee> getAllEmployees() {
		return employeeRepository.findAll();
	}
}
